export const HomeObjTwo = {
    proj: true,
    element: 'blog',
    status: true,
    lightBg: false,
    primary: false,
    imgStart: '', 
    lightTopLine: false, 
    lightTextDesc: false, 
    buttonLabel: 'Portfolio', 
    description: 'view all>', 
    main: "latest",
    mainBold: "Blog", 
    lightText: false, 
    topLine: '',
    start: '',
    img : require('../../images/homepage/Thumb.jpg').default,
    alt : 'Header Image',
    link: "/Blogs"
}