export { default as Navbar } from './Navbar/Navbar'
export { default as Section } from './Section/Section'
export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Gradient } from './Gradient/Gradient'
export { default as Catalog } from './CatalogComponent/Catalog';
export { default as Socials } from './Socials/Socials';
export { default as SocialDetailsHM } from './SocialsDetailsHM/SocialDetailsHM';
export { default as SocialsDetails } from './SocialsDetails/SocialsDetails';